modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/gigaherz/JsonMerger/issues"
license="BSD (3 clause)"

[[mods]]
    modId="jsonmerger"
    version="${file.jarVersion}"
    logoFile="logo.png"
    displayName="Json Merger"
    displayURL="https://github.com/gigaherz/JsonMerger/"
    authors="gigahez"
    description='''
A small mod/coremod to allow merging jsons that would otherwise overwrite each other.
'''

[[dependencies.jsonmerger]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jsonmerger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="BOTH"
